# TODO: create separate services for prod environments

services:
  client:
    container_name: trivia-party-client
    build:
      context: client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: client
          target: /app/client
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json